//! Where the TypeScript the React app imports comes from.
//!
//! The React app does not hand-write the shape of a command. It imports
//! [`BINDINGS_FILE`], which this module generates from the same command list
//! Tauri dispatches on, so a change to a Rust signature is a change to the
//! TypeScript by construction rather than by anyone remembering.
//!
//! Generated code that is committed drifts the moment someone edits Rust and
//! does not re-run the generator. Two things stop that here:
//!
//! - [`generate`] produces the file's contents, and `tests/bindings.rs` fails
//!   when the committed file differs from it. `cargo test --workspace` is
//!   therefore the drift check.
//! - `cargo run -p trdr-desktop --bin export-bindings` writes the file. The
//!   failing test says so, so the fix is in front of whoever hits it.

use crate::builder;
use specta_typescript::Typescript;
use std::path::{Path, PathBuf};

/// The generated file's name inside the React source directory.
pub const BINDINGS_FILE: &str = "bindings.ts";

/// What the header of the generated file must say, so nobody edits it by hand.
const HEADER: &str = "\
// Generated by tauri-specta from the commands in `src-tauri/src/commands.rs`.
// Do not edit: run `cargo run -p trdr-desktop --bin export-bindings` instead.
// `cargo test --workspace` fails when this file and those commands disagree.
";

/// The React source directory the generated file belongs in.
pub fn react_source_directory() -> PathBuf
{
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("src-tauri always sits inside the desktop app directory")
        .join("src")
}

/// The absolute path of the generated file.
///
/// Built by walking up rather than by joining `../src`, so the result has no
/// `..` component in it and comparing it against another path means what it
/// looks like it means.
pub fn bindings_path() -> PathBuf
{
    react_source_directory().join(BINDINGS_FILE)
}

/// The TypeScript the current command list produces.
///
/// tauri-specta writes to a file rather than returning a string, so this
/// generates into a temporary directory and reads the result back. That keeps
/// the drift test and the exporter running the exact same code path — a check
/// that reimplements what it checks is a check that agrees with itself and not
/// with the build.
pub fn generate() -> Result<String, Box<dyn std::error::Error>>
{
    let directory = std::env::temp_dir().join(format!(
        "trdr-bindings-{}-{:?}",
        std::process::id(),
        std::thread::current().id()
    ));
    std::fs::create_dir_all(&directory)?;

    let scratch = directory.join("bindings.ts");
    // Why the exporter is allowed to write a 64-bit integer as `number`:
    //
    // One `i64` crosses this boundary — `ErrorParam::Integer`, which carries the
    // counts and limits an error message renders. specta refuses those by
    // default because `JSON.parse` silently truncates past 2^53, and it is right
    // to. Here the truncation is not something this flag introduces: the value
    // already travels as a JSON number, so a WebView receives a JavaScript
    // `number` whatever the type declaration says. `number` describes what
    // arrives; `bigint` would describe something that does not.
    //
    // What the flag does risk is the next 64-bit field, which would be typed
    // lossily without anyone deciding to. `tests/bindings.rs` pins the exported
    // type list for that reason: a new type reaching the WebView fails a test,
    // and whoever updates the list is the person who has to look at this.
    let generated = builder::commands::<tauri::Wry>()
        .dangerously_cast_bigints_to_number()
        .export(Typescript::default().header(HEADER), &scratch);

    // The temporary directory goes away whether the export worked or not, so a
    // failed run does not leave a stale file for the next one to read.
    let contents = generated.and_then(|()| Ok(std::fs::read_to_string(&scratch)?));
    std::fs::remove_dir_all(&directory)?;

    Ok(contents?)
}

/// Writes the generated TypeScript over the committed file.
pub fn export() -> Result<PathBuf, Box<dyn std::error::Error>>
{
    let path = bindings_path();
    std::fs::write(&path, generate()?)?;
    Ok(path)
}
