// Generated by tauri-specta from the commands in `src-tauri/src/commands.rs`.
// Do not edit: run `cargo run -p trdr-desktop --bin export-bindings` instead.
// `cargo test --workspace` fails when this file and those commands disagree.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  A typed round-trip, and the proof that the bridge carries validated types.
	 * 
	 *  The argument is a [`RequestId`], not a string. That is what makes this a real
	 *  test of the boundary rather than a test of `invoke`: `RequestId` crosses to
	 *  TypeScript as a plain `string`, and is parsed back into a 26-character ULID
	 *  on the way in, so a WebView that sends anything else is refused by
	 *  deserialisation before this function is entered.
	 */
	ping: (id: string) => __TAURI_INVOKE<PingResponse_Serialize>("ping", { id }),
	/**  Answers `bootstrap.get` from the workspace this process opened at start-up. */
	bootstrapGet: (id: string) => __TAURI_INVOKE<BootstrapResponse_Serialize>("bootstrap_get", { id }),
	/**
	 *  Starts the agent terminal, and opens the two channels it speaks through
	 *  (section 9.1's `terminal.start`).
	 * 
	 *  Both channels are arguments rather than events. Events would need the
	 *  WebView to be granted `core:event:listen`, which is a general ability to
	 *  listen to anything the host emits; a channel is created by the caller, passed
	 *  to one command, and reaches nothing else. `capabilities/main.json` therefore
	 *  stays a list of four terminal commands rather than four commands and a
	 *  permission that also covers everything added later.
	 * 
	 *  Calling this twice does not start a second agent. A WebView that reloaded has
	 *  no way to know whether the host still has a terminal, so the answer is the
	 *  one that is running, with the scrollback replayed down the output channel
	 *  before anything live.
	 */
	terminalStart: (id: string, output: Channel<TerminalOutput>, lifecycle: Channel<TerminalProcessEvent>) => __TAURI_INVOKE<TerminalStartResponse_Serialize>("terminal_start", { id, output, lifecycle }),
	/**  Sends keystrokes to the agent (section 9.1's `terminal.input`). */
	terminalInput: (id: string, input: TerminalInputParams) => __TAURI_INVOKE<TerminalInputResponse_Serialize>("terminal_input", { id, input }),
	/**
	 *  Tells the agent the terminal changed size (section 9.1's `terminal.resize`).
	 * 
	 *  A size that arrives with no child running is kept rather than refused; see
	 *  [`trdr_runtime::pty::TerminalSession::resize`] for why that is the whole
	 *  answer to the race between a screen laying itself out and a process starting.
	 */
	terminalResize: (id: string, size: TerminalResizeParams) => __TAURI_INVOKE<TerminalResizeResponse_Serialize>("terminal_resize", { id, size }),
	/**
	 *  Stops the agent and starts it again (section 9.1's `terminal.restart`).
	 * 
	 *  The channels are the ones the last [`terminal_start`] opened. A restart is
	 *  the same terminal with a new child in it, not a new terminal.
	 */
	terminalRestart: (id: string) => __TAURI_INVOKE<TerminalRestartResponse_Serialize>("terminal_restart", { id }),
};

/* Types */
/**
 *  What the app needs before it can show anything (section 9.1's `bootstrap.get`).
 * 
 *  Five fields, and the list is meant to stay short. Section 11 gives every
 *  screen its own query model; this is only what has to be true before the first
 *  screen can be drawn at all — which workspace is open, what build is running,
 *  and what the two versions on the wire are.
 * 
 *  # The workspace path, and why a screen is allowed to see one
 * 
 *  Section 9.1 forbids a screen from *passing* a path: it names a location with
 *  a [`trdr_core::id::ScopedPathHandle`] the host minted after a native picker,
 *  so it can never name a file the user did not choose. Being told where the
 *  open workspace is, is the other direction and a different question. The host
 *  chose it, the person is entitled to know it, and the alternative — a screen
 *  that cannot say which workspace it is showing — is worse. What stays out of
 *  reach is the general ability to resolve paths, which is why the capability
 *  file grants no `core:path` permission and `tests/capability.rs` checks.
 */
export type BootstrapModel = {
	/**  The IPC protocol version this build speaks. */
	protocol_version: number,
	/**  The app's own version. */
	app_version: string,
	/**  The portable identity of the workspace that is open. */
	workspace_id: string,
	/**  Where that workspace is on disk. */
	workspace_path: string,
	/**  The schema version of its database. */
	schema_version: number,
};

/**
 *  The envelope [`bootstrap_get`] answers with.
 * 
 *  Transparent, for the reason the module documentation gives.
 */
export type BootstrapResponse = BootstrapResponse_Serialize | BootstrapResponse_Deserialize;

/**
 *  The envelope [`bootstrap_get`] answers with.
 * 
 *  Transparent, for the reason the module documentation gives.
 */
export type BootstrapResponse_Deserialize = UiResponseEnvelope_Deserialize<BootstrapModel>;

/**
 *  The envelope [`bootstrap_get`] answers with.
 * 
 *  Transparent, for the reason the module documentation gives.
 */
export type BootstrapResponse_Serialize = UiResponseEnvelope_Serialize<BootstrapModel>;

/**
 *  The `v` field of a versioned message.
 * 
 *  A value of this type can only exist for a version this binary supports, so
 *  code downstream of parsing never has to re-check it.
 */
export type EnvelopeVersion = number;

/**
 *  Every failure trdr can report.
 * 
 *  The set is closed and comes from section 12. A new kind of failure gets a new
 *  variant here rather than a new sentence somewhere, and the exhaustive match in
 *  [`ErrorCode::family`] means adding one is a compile error until it has been
 *  placed in a family.
 */
export type ErrorCode = 
/**  No credential is stored for this source. */
"AUTH_MISSING" | 
/**
 *  The stored credential was refused by the source.
 * 
 *  Distinct from [`ErrorCode::UpstreamUnavailable`] on purpose: this one is
 *  the user's to fix.
 */
"AUTH_INVALID" | 
/**  The source is refusing further calls for now. */
"AUTH_RATE_LIMITED" | 
/**  The source could not be reached, or refused to serve. */
"UPSTREAM_UNAVAILABLE" | 
/**  The source did not answer in time. */
"UPSTREAM_TIMEOUT" | 
/**  The source answered with something trdr cannot read. */
"UPSTREAM_MALFORMED" | 
/**  A bundle did not match its declared schema. */
"BUNDLE_SCHEMA" | 
/**  A bundle file did not match its recorded hash. */
"BUNDLE_HASH" | 
/**  A bundle was larger than the limits allow. */
"BUNDLE_SIZE" | 
/**  A bundle record contradicts one already stored. */
"BUNDLE_CONFLICT" | 
/**  The data needed for this does not cover the range asked for. */
"DATA_INCOMPLETE" | 
/**  The data is of a kind this version does not support. */
"DATA_UNSUPPORTED" | 
/**  A value would have been used before it could have been known. */
"DATA_FUTURE_LEAK" | 
/**  Stored data failed its own consistency check. */
"DATA_INTEGRITY" | 
/**  A strategy file could not be read as a strategy. */
"STRATEGY_SYNTAX" | 
/**  A strategy asked for a rule this engine does not implement. */
"STRATEGY_UNSUPPORTED_RULE" | 
/**  A strategy named a period that cannot be run. */
"STRATEGY_INVALID_PERIOD" | 
/**  The database is held by someone else right now. */
"DB_BUSY" | 
/**  A schema migration could not be applied. */
"DB_MIGRATION" | 
/**  The database failed its integrity check. */
"DB_INTEGRITY" | 
/**  There is no room left on the disk. */
"DB_DISK_FULL" | 
/**  A backup package could not be authenticated or decrypted. */
"BACKUP_AUTHENTICATION" | 
/**  A backup package failed a checksum. */
"BACKUP_CHECKSUM" | 
/**  A backup package is from a version this build cannot read. */
"BACKUP_UNSUPPORTED_VERSION" | 
/**  A backup package is missing part of itself. */
"BACKUP_INCOMPLETE" | 
/**  The app is not running, so this cannot be done. */
"APP_NOT_RUNNING" | 
/**  The message did not fit the protocol. */
"APP_PROTOCOL_VERSION" | 
/**  The caller is not allowed to ask for this. */
"APP_PERMISSION" | 
/**  A person rejected the request. */
"APPROVAL_REJECTED" | 
/**  The request was not answered in time. */
"APPROVAL_EXPIRED" | 
/**  What was approved is no longer what would happen. */
"APPROVAL_STALE" | 
/**  The requester went away before the answer came. */
"APPROVAL_DISCONNECTED" | 
/**  The agent executable is not where it was expected. */
"TERMINAL_EXECUTABLE_MISSING" | 
/**  The agent process could not be started. */
"TERMINAL_SPAWN" | 
/**  The agent process ended. */
"TERMINAL_EXITED";

/**
 *  A failure, in the form every surface receives it.
 * 
 *  Built through [`ErrorEnvelope::new`] and the `with_*` methods so that the
 *  version is always set and the parameter rules always run.
 */
export type ErrorEnvelope = ErrorEnvelope_Serialize | ErrorEnvelope_Deserialize;

/**
 *  A failure, in the form every surface receives it.
 * 
 *  Built through [`ErrorEnvelope::new`] and the `with_*` methods so that the
 *  version is always set and the parameter rules always run.
 */
export type ErrorEnvelope_Deserialize = {
	/**  Protocol version, the same field the IPC frames carry. */
	v: EnvelopeVersion,
	/**
	 *  The request this failure answers, when it answers one.
	 * 
	 *  Absent for a failure that happened outside a request, such as one during
	 *  start-up.
	 */
	id?: string | null,
	/**  What went wrong, as a value a caller can branch on. */
	code: ErrorCode,
	/**  Named values the surface may put into its own sentence. */
	params?: { [key in string]: ErrorParam },
	/**  Whether trying again could work. */
	retryability: Retryability,
	/**  Points at the full cause chain in the local log. */
	cause_chain_id?: string | null,
	/**  What the upstream said, when an upstream said anything. */
	upstream?: UpstreamStatus_Deserialize | null,
};

/**
 *  A failure, in the form every surface receives it.
 * 
 *  Built through [`ErrorEnvelope::new`] and the `with_*` methods so that the
 *  version is always set and the parameter rules always run.
 */
export type ErrorEnvelope_Serialize = {
	/**  Protocol version, the same field the IPC frames carry. */
	v: EnvelopeVersion,
	/**
	 *  The request this failure answers, when it answers one.
	 * 
	 *  Absent for a failure that happened outside a request, such as one during
	 *  start-up.
	 */
	id?: string | null,
	/**  What went wrong, as a value a caller can branch on. */
	code: ErrorCode,
	/**  Named values the surface may put into its own sentence. */
	params?: { [key in string]: ErrorParam },
	/**  Whether trying again could work. */
	retryability: Retryability,
	/**  Points at the full cause chain in the local log. */
	cause_chain_id?: string | null,
	/**  What the upstream said, when an upstream said anything. */
	upstream?: UpstreamStatus_Serialize | null,
};

/**
 *  A value an error carries for a surface to put into its own sentence.
 * 
 *  The variants are small on purpose. There is no "any JSON" variant, because
 *  that is how an upstream response body ends up on a screen.
 */
export type ErrorParam = 
/**  A short piece of text, at most [`MAX_PARAM_TEXT_BYTES`] bytes. */
{ type: "text"; value: string } | 
/**  A whole number, such as a count or a limit. */
{ type: "integer"; value: number } | 
/**  A flag. */
{ type: "boolean"; value: boolean };

/**
 *  The envelope [`ping`] answers with, named so the bindings can describe it.
 * 
 *  Transparent: this is `UiResponseEnvelope<Pong>` on the wire and in the
 *  generated TypeScript alike. See the module documentation for why the name
 *  exists at all.
 */
export type PingResponse = PingResponse_Serialize | PingResponse_Deserialize;

/**
 *  The envelope [`ping`] answers with, named so the bindings can describe it.
 * 
 *  Transparent: this is `UiResponseEnvelope<Pong>` on the wire and in the
 *  generated TypeScript alike. See the module documentation for why the name
 *  exists at all.
 */
export type PingResponse_Deserialize = UiResponseEnvelope_Deserialize<Pong>;

/**
 *  The envelope [`ping`] answers with, named so the bindings can describe it.
 * 
 *  Transparent: this is `UiResponseEnvelope<Pong>` on the wire and in the
 *  generated TypeScript alike. See the module documentation for why the name
 *  exists at all.
 */
export type PingResponse_Serialize = UiResponseEnvelope_Serialize<Pong>;

/**
 *  What [`ping`] answers with.
 * 
 *  Deliberately not part of `trdr-core`: this is a liveness check on the bridge
 *  between the WebView and the host, not a contract between the app and the CLI.
 */
export type Pong = {
	/**
	 *  The protocol version this build speaks, so the screen learns it from the
	 *  same round-trip that proved the bridge works.
	 */
	protocol_version: number,
};

/**  Whether trying the same thing again could work. */
export type Retryability = 
/**  Retrying changes nothing; something has to change first. */
{ kind: "no" } | 
/**  Retrying now is reasonable. */
{ kind: "immediate" } | 
/**  Retrying is reasonable after waiting. */
{ kind: "after_seconds"; 
/**  How long to wait. */
seconds: number };

/**  What the terminal answers to a keystroke or a resize. */
export type TerminalAcknowledged = {
	/**  Where the process is now. */
	process: TerminalProcess,
};

/**  Keystrokes for the agent terminal. */
export type TerminalInputParams = {
	/**
	 *  Raw bytes, base64 encoded.
	 * 
	 *  Bytes, not text: section 1 says the agent's output is a byte stream and
	 *  nothing on the way through interprets it. The same holds going in.
	 */
	data_base64: string,
};

/**  The envelope [`terminal_input`] answers with. Transparent. */
export type TerminalInputResponse = TerminalInputResponse_Serialize | TerminalInputResponse_Deserialize;

/**  The envelope [`terminal_input`] answers with. Transparent. */
export type TerminalInputResponse_Deserialize = UiResponseEnvelope_Deserialize<TerminalAcknowledged>;

/**  The envelope [`terminal_input`] answers with. Transparent. */
export type TerminalInputResponse_Serialize = UiResponseEnvelope_Serialize<TerminalAcknowledged>;

/**
 *  One chunk of the agent's output, on its way to the terminal in the WebView.
 * 
 *  Base64 for the reason [`trdr_runtime::base64`] gives and the reason
 *  [`TerminalInputParams`] already gives for the other direction: terminal
 *  traffic is not text, a read can end in the middle of a character, and
 *  anything that converted the stream would replace what it could not decode.
 */
export type TerminalOutput = {
	/**  Raw bytes, base64 encoded. */
	data_base64: string,
};

/**
 *  The seven process states the visual contract fixes.
 * 
 *  Five of them are what [`PtyLifecycle`] can report, and the mapping below is
 *  the whole of the translation. The other two have no producer on this path and
 *  cannot get one:
 * 
 *  - `needs-input` would have to be read out of the agent's own output, and
 *    section 11 forbids turning terminal content into product state in either
 *    direction. There is no prompt detector here and there is not going to be
 *    one.
 *  - `approval-pending` belongs to the registration approval round-trip in
 *    section 9.3, which is milestone M6. When it exists it will be produced by
 *    the approval broker, which knows about pending requests, and not by the
 *    terminal, which does not.
 * 
 *  M2 still has to show all seven, because the whole app in M2 runs on a
 *  synthetic fixture. That is the surface's job and it is done in TypeScript,
 *  where the fixture producer lives beside the live one and is marked as
 *  synthetic — see `apps/desktop/src/terminal/processState.ts`. Nothing on this
 *  path can produce a state the host did not observe.
 */
export type TerminalProcess = 
/**  A start has been asked for and no child exists yet. */
"starting" | 
/**  A child is running and has printed nothing. */
"ready" | 
/**  The child has printed something. */
"running" | 
/**  The agent is waiting for the person to answer it. No producer in M2. */
"needs-input" | 
/**  An approval sheet is open for this agent. No producer until M6. */
"approval-pending" | 
/**  No child is running. */
"exited" | 
/**  The previous child is being stopped and a new one started. */
"reconnecting";

/**
 *  A process-state change, on its way to the status bar.
 * 
 *  One field, and it is deliberately the only one. Section 9.1 separates
 *  host-to-UI state events from the terminal byte stream, and a type with
 *  nowhere to put a byte is a stronger separation than a rule about where not to
 *  put one.
 */
export type TerminalProcessEvent = {
	/**  Where the process is now. */
	process: TerminalProcess,
};

/**  A new terminal size. */
export type TerminalResizeParams = {
	/**  Columns. */
	cols: number,
	/**  Rows. */
	rows: number,
};

/**  The envelope [`terminal_resize`] answers with. Transparent. */
export type TerminalResizeResponse = TerminalResizeResponse_Serialize | TerminalResizeResponse_Deserialize;

/**  The envelope [`terminal_resize`] answers with. Transparent. */
export type TerminalResizeResponse_Deserialize = UiResponseEnvelope_Deserialize<TerminalAcknowledged>;

/**  The envelope [`terminal_resize`] answers with. Transparent. */
export type TerminalResizeResponse_Serialize = UiResponseEnvelope_Serialize<TerminalAcknowledged>;

/**  The envelope [`terminal_restart`] answers with. Transparent. */
export type TerminalRestartResponse = TerminalRestartResponse_Serialize | TerminalRestartResponse_Deserialize;

/**  The envelope [`terminal_restart`] answers with. Transparent. */
export type TerminalRestartResponse_Deserialize = UiResponseEnvelope_Deserialize<TerminalSessionModel>;

/**  The envelope [`terminal_restart`] answers with. Transparent. */
export type TerminalRestartResponse_Serialize = UiResponseEnvelope_Serialize<TerminalSessionModel>;

/**  What a start or a restart settled. */
export type TerminalSessionModel = {
	/**
	 *  The agent as the setting names it.
	 * 
	 *  The configured name, never the location this process resolved it to. The
	 *  screen has no reason to learn where a person keeps their tools.
	 */
	agent: string,
	/**  The child's process id, where the system gave one. */
	pid: number | null,
	/**  Where the process is now. */
	process: TerminalProcess,
	/**  Columns the child was told about. */
	cols: number,
	/**  Rows the child was told about. */
	rows: number,
};

/**
 *  The envelope [`terminal_start`] answers with. Transparent; see the module
 *  documentation.
 */
export type TerminalStartResponse = TerminalStartResponse_Serialize | TerminalStartResponse_Deserialize;

/**
 *  The envelope [`terminal_start`] answers with. Transparent; see the module
 *  documentation.
 */
export type TerminalStartResponse_Deserialize = UiResponseEnvelope_Deserialize<TerminalSessionModel>;

/**
 *  The envelope [`terminal_start`] answers with. Transparent; see the module
 *  documentation.
 */
export type TerminalStartResponse_Serialize = UiResponseEnvelope_Serialize<TerminalSessionModel>;

/**  Either a result or an error envelope, never both and never neither. */
export type UiOutcome<T> = UiOutcome_Serialize<T> | UiOutcome_Deserialize<T>;

/**  Either a result or an error envelope, never both and never neither. */
export type UiOutcome_Deserialize<T> = 
/**  The command succeeded, and this is what it produced. */
{ status: "ok"; value: T } | 
/**  The command failed. */
{ status: "error"; value: ErrorEnvelope_Deserialize };

/**  Either a result or an error envelope, never both and never neither. */
export type UiOutcome_Serialize<T> = 
/**  The command succeeded, and this is what it produced. */
{ status: "ok"; value: T } | 
/**  The command failed. */
{ status: "error"; value: ErrorEnvelope_Serialize };

/**  The answer to a [`UiCommandEnvelope`]. */
export type UiResponseEnvelope<T> = UiResponseEnvelope_Serialize<T> | UiResponseEnvelope_Deserialize<T>;

/**  The answer to a [`UiCommandEnvelope`]. */
export type UiResponseEnvelope_Deserialize<T> = {
	/**  Protocol version. */
	v: EnvelopeVersion,
	/**  The command this answers. */
	id: string,
	/**  How it went. */
	outcome: UiOutcome_Deserialize<T>,
};

/**  The answer to a [`UiCommandEnvelope`]. */
export type UiResponseEnvelope_Serialize<T> = {
	/**  Protocol version. */
	v: EnvelopeVersion,
	/**  The command this answers. */
	id: string,
	/**  How it went. */
	outcome: UiOutcome_Serialize<T>,
};

/**
 *  What an upstream said, kept beside trdr's own code.
 * 
 *  This is the status line and the upstream's own short code, never a header or
 *  a body. It exists so that a `401` from a broker and an unreachable broker
 *  stay two different facts all the way to the screen, and so that a support
 *  question can be answered without turning logging back on.
 */
export type UpstreamStatus = UpstreamStatus_Serialize | UpstreamStatus_Deserialize;

/**
 *  What an upstream said, kept beside trdr's own code.
 * 
 *  This is the status line and the upstream's own short code, never a header or
 *  a body. It exists so that a `401` from a broker and an unreachable broker
 *  stay two different facts all the way to the screen, and so that a support
 *  question can be answered without turning logging back on.
 */
export type UpstreamStatus_Deserialize = {
	/**  The HTTP status, when the exchange got far enough to have one. */
	http_status?: number | null,
	/**  The upstream's own short status code, when it publishes one. */
	upstream_code?: string | null,
};

/**
 *  What an upstream said, kept beside trdr's own code.
 * 
 *  This is the status line and the upstream's own short code, never a header or
 *  a body. It exists so that a `401` from a broker and an unreachable broker
 *  stay two different facts all the way to the screen, and so that a support
 *  question can be answered without turning logging back on.
 */
export type UpstreamStatus_Serialize = {
	/**  The HTTP status, when the exchange got far enough to have one. */
	http_status?: number | null,
	/**  The upstream's own short status code, when it publishes one. */
	upstream_code?: string | null,
};

